### PR TITLE
Transfer JSON training configuration keys into properties in the TrainingConfiguration class

### LINKED ISSUE #18: Transfer training configuration JSON properties into class properties
Currently, we are storing the training configuration for data distribution and node dropping as a JSON object in the code.

https://github.com/bnnthang/RealFL/blob/c3510b7dfc32b54e74eda4207fc335fc3c82d837/CommonUtils/src/main/java/com/bnnthang/fltestbed/commonutils/models/TrainingConfiguration.java#L53

This is not a good practice as we need to keep using the JSON utility methods to extract the values we want. Instead, for each key-value pair in the JSON configuration file, create a variable in the `TrainingConfiguration` class (with a suitable data type). For example, we want to store the key-value-pair `"evenLabelDistributionByClient": true` as a boolean variable.

### PR DESCRIPTION
**Pull request by ttanv**
This PR is to close #18.

### CODE REVIEW

**Comment by ttanv** [comment]
@bnnthang if you check Server/App.java, you'll see that I set values of TrainingConfiguration that can be null (i.e. don't have @NonNull over them) using the "set....." method, instead of passing it in as parameter to training constructor. Is there a way to pass them as parameters to constructor?

**Comment by bnnthang** [comment]
The TrainingConfiguration class is annotated with Data. You should be able to pass all arguments via a constructor. Check this out https://projectlombok.org/features/Data.

**Comment by thangnbn** [comment]
> @bnnthang if you check Server/App.java, you'll see that I set values of TrainingConfiguration that can be null (i.e. don't have @nonnull over them) using the "set....." method, instead of passing it in as parameter to training constructor. Is there a way to pass them as parameters to constructor?

The TrainingConfiguration class is annotated with Data. You should be able to pass all arguments via a constructor. Check this out https://projectlombok.org/features/Data.

By the way, this also fixes #26 right?

**Comment by ttanv** [comment]
Yes, I already did. But for some reason, only arguments with the @NonNull constructor are recognized.

**Comment by ttanv** [comment]
I think I unintentionally fixed some parts of #26. I think its best if I take another look after I finish #18 and #19

**Comment by thangnbn** [comment]
> Yes, I already did. But for some reason, only arguments with the @nonnull constructor are recognized.

I think you can look at this as well https://projectlombok.org/features/constructor. In short, you just need to add the AllArgsConstructor annotation, I think.

**Comment by thangnbn** [comment]
@tem556 Have you finished? Let me know, and I will close this PR. Your new commit is included here as well.

**Comment by ttanv** [comment]
Yes I am done

**Review by thangnbn — COMMENTED** [review]
This is just to close the PR. Everything was good by the time of this comment.

**Pull request merged**
